unstable_features = true

format_strings = true

max_width = 100
newline_style = "Unix"
blank_lines_upper_bound = 1

overflow_delimited_expr = false
struct_lit_single_line = true
combine_control_expr = false

comment_width = 100
wrap_comments = true
normalize_comments = true

imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

match_block_trailing_comma = true

use_field_init_shorthand = true

force_multiline_blocks = true
